import { Public_Sans} from "next/font/google";
import "./globals.css";

const publicSance = Public_Sans({
  variable: "--font-Public_Sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${publicSance.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
